.\" Manpage for minecraft_update
.TH man 1 "31 March 2018" "1.1" "minecraft_update man page"
.SH NAME
.B "minecraft_update" 
\- update the Minecraft server jar file
.SH SYNOPSIS
.B "minecraft_update"
.SH DESCRIPTION
.B "minecraft_update"
downloads the latest minecraft server file to the current working directory and creates a symlink to it called minecraft_server.jar. It can parse the version of the existing server file to determine if it is out of date, and replace it.
.SH BUGS
Probably lots. Error checking is minimal.
.SH AUTHOR
David Mahoney (clawmaster@gmail.com)
